language: go

go:
  - 1.9.x
  - master

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide -y
  - glide install
  - glide up

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
