language: go

go:
  - 1.9.x
  - master

install:
  - go get -u github.com/labstack/echo
  - go get -u github.com/aymerick/raymond
  - go get -u github.com/sirupsen/logrus
  - go get -u github.com/rs/xid
  - go get -u github.com/stretchr/testify
  - go get -u github.com/labstack/echo/middleware

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
